dist: xenial
language: cpp

matrix:
  include:
    - addons:
        apt:
          packages:
            - g++-4.9
      compiler: g++-4.9
      env:
        - CXXSTD=11
    - addons:
        apt:
          packages:
            - clang-3.9
      compiler: clang-3.9
      env:
        - CXXSTD=11
    - addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
      compiler: g++-7
      env:
        - CXXSTD=17
    - addons:
        apt:
          packages:
            - clang-7
          sources:
            - llvm-toolchain-xenial-7
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      compiler: clang-7
      env:
        - CXXSTD=17

install:
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xf release-1.8.0.tar.gz
  - cd googletest-release-1.8.0
  - cmake -DBUILD_SHARED_LIBS=ON .
  - make
  - sudo make install
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake -DBITSERY_BUILD_TESTS=ON -DCMAKE_CXX_STANDARD=$CXXSTD ..

script:
  - make
  - cd tests
  - ctest

